---
title: "20180114_Retene_calib_Ari'sruns"
author: "GB"
date: "1/14/2018"
output: html_document
---

---
title: '20180107'
author: "GB"
date: "1/7/2018"
output: html_document
---

```{r "cleanup", echo = FALSE, eval=FALSE}
# not run in knitted doc
rm(list = ls())
.rs.restartR()
```

```{r "load libraries", echo = FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(plotly)
library(stringr)
library(knitr)
library(readxl)
library(tidyr)
library(purrr)
#library(xlsx)
opts_chunk$set(dev=c("png", "pdf"), dev.args=list(pdf = list(encoding="WinAnsi", useDingbats=FALSE)),
  fig.keep="all", fig.path = file.path("plots", "smoky_hollows_SRM")) ### CHANGE PLOT SUFFIX ###
```

#Read and organize data
```{r}
read_srm_export <- function(filename, columns = c("peak_name", "RT.min", "basepeak", "area.cpm", "height.cts", "quantitation")) {
  filename %>% 
    # read excel files
    read_excel(sheet = "Integration", skip = 42, 
               col_names = columns, col_types = rep("text", length(columns))) %>% 
    as_data_frame() %>%
    # remove empty rows
    filter(!is.na(peak_name), peak_name != "n.a.") %>% 
    # convert the relevant numeric columns into numbers
    mutate_at(vars(RT.min, area.cpm, height.cts), as.numeric) %>% 
    # remove useless columns
    select(-basepeak, -quantitation) %>% 
    # add filename info
    mutate(file_id = gsub("\\.xls", "", basename(filename))) %>% 
    select(file_id, everything())
}

# get data
all_data <- 
  # find all excel files
  list.files("data_reports", recursive = TRUE, full.names = TRUE, pattern = "\\.xls$") %>% 
  # send them to the read method
  lapply(read_srm_export) %>% 
  # combine the data set
  bind_rows() %>% 
  # pull out sample information
  #mutate(sample_id = str_match(all_data$file_id, "TSQ\\d+_GB_(.*)$") %>% { .[,2] }) %>% 
  # get n replicates
  group_by(file_id)
  #mutate(n_replicates = length(unique(file_id)))

```

#File names for metadata file
```{r, echo=FALSE, eval=FALSE}
# file names
all_data$file_id %>% unique() %>%  paste(collapse = "\n") %>% message()
```

#Plot to check the spread
##by sequence
```{r}
all_data %>% 
  ggplot() + 
  aes(x = peak_name, y = area.cpm, color = file_id) +
  geom_point(size = 3) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```
##by sample
```{r}
all_data %>% 
  ggplot() +
  aes(x = file_id, y = area.cpm, color = file_id) + 
  geom_point(size = 3) +
  facet_wrap(~peak_name, scales = "free_y") +
    theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        legend.position = "none")
```

# Calculation peak amounts and rock concentrations, ID standards

```{r}
depth_and_rock_info <- read_excel(file.path("metadata", "aliphaticSRM_20180109.xlsx")) %>% 
  rename(rock.g = `rock`) %>% 
  filter(!is.na(file_id))
kable(depth_and_rock_info)


data_by_depth <- 
  all_data %>%
  left_join(depth_and_rock_info, by = "file_id") %>% 
  group_by(file_id) %>% 
  mutate(
    n_peaks = n(),
    n_standards = sum(peak_name == "D4 C29 ISTD"),
    ref_area.cpm = area.cpm[peak_name == "D4 C29 ISTD"],
    ref_amount_added.ug = 1, #check standard amount added
    amount.ug = area.cpm/ref_area.cpm * ref_amount_added.ug,
    conc_rock.ug_g = amount.ug / rock.g, 
    #total_area.cpm = sum(area.cpm[peak_name != "d14-pTerph"]),
    #area.percent = area.cpm / total_area.cpm * 100
    n_injec_std = sum(peak_name == "Retene (InjSt)"),
    injec_std_area.cpm = area.cpm[peak_name == "Retene (InjSt)"],
    injec_std_added.ug = .005 #in ug
  )%>% ungroup() %>% 
  arrange(file_id, peak_name) 

View(data_by_depth)
```

##Calculate and correct for injection volume

### Linear regressions of the calibration curves

```{r}
inj.standard <- read_excel(file.path("metadata", "Retene_calibration.xlsx"))   ###read excel

###Retene calibration curve
inj.standard %>% 
  ggplot() +
  aes(x = Known.ng, y = Measured_area.counts, color = calibration) + 
  geom_smooth(method = "lm", alpha = 0.5) +
  geom_point() +
  theme_bw() +
  theme(legend.position = "none") 

inj.calibrations <- 
  inj.standard %>% 
  filter(!is.na(calibration)) %>% 
  nest(-calibration) %>% 
  mutate(
    fit = map(data, ~summary(lm(`Measured_area.counts`~ `Known.ng`, data = .x))),
    coefficients = map(fit, "coefficients"),
    intercept = map_dbl(coefficients, `[`, 1, 1),
    intercept_se = map_dbl(coefficients, `[`, 1, 2),
    slope = map_dbl(coefficients, `[`, 2, 1),
    slope_se = map_dbl(coefficients, `[`, 2, 2),
    r2 = map_dbl(fit, "r.squared")
  )

View(inj.calibrations)
inj.calibrations %>% select(-data, -fit, -coefficients) %>% knitr::kable(d = 3)
```

### Calculate injection amount
```{r}
data_w_inject <-
  data_by_depth %>% 
  # temp
  mutate(calibration = "jan2018") %>% 
  left_join(inj.calibrations, by = "calibration") %>% 
  mutate(
    total_volume.uL = 100,
    total_inject.uL = 1.5,
    retene_amount_inject_expected.ng = ((injec_std_added.ug/total_volume.uL) * total_inject.uL)*1000,
    retene_amount_inject_measured.ng = (injec_std_area.cpm - intercept)/slope,
    retene_amount_measured.ug = total_volume.uL/total_inject.uL * retene_amount_inject_measured.ng * 1/1000,
    inject_percent = (retene_amount_inject_measured.ng/retene_amount_inject_expected.ng)*100
  )
  
View(data_w_inject)
#calib_data_corr <- calib_data %>% mutate(conc_rock.ug_g = amount_yield_corr.ug / `rock `) #in microgram lipid per gram rock
#View(calib_data_corr)

data_w_inject %>% 
  ggplot() +
  aes(x = file_id, y = inject_percent) + 
  geom_smooth(method = "lm", alpha = 0.5) +
  geom_point() +
  theme_bw() +
  theme(legend.position = "none") 
```

